version: '3.8'
services:
  bark-server:
    image: adams549659584/bark-server
    container_name: bark-server
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"